### ISSUE TITLE
Error compiling with latest beta of esphome

### ISSUE THREAD

**Issue by shbatm** [hencou/esphome-milight#4]
Receiving the following errors trying to compile on [v2022.12.0b1](https://beta.esphome.io/) of ESPHome.

Compiling the same code that worked a few days ago (trying to setup 2nd device). Sorry to dump and run, but have family coming tomorrow so I don't have time to troubleshoot more at the moment.

Tried clearing build cache and re-pinned to the last version I used in the repo just to make sure your latest updates didn't do anything.

```shell
Compiling /data/milight-bridge-back/.pioenvs/milight-bridge-back/libf5f/milight/lib/MiLight/FUT02xPacketFormatter.cpp.o
In file included from /data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/../MiLight/PacketFormatter.h:6,
                 from /data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/CctPacketFormatter.h:1,
                 from /data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/CctPacketFormatter.cpp:1:
/data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/../MiLight/../MiLightState/GroupState.h:127:64: error: 'std::vector' has not been declared
   void applyState(JsonObject state, const BulbId& bulbId, std::vector<GroupStateField>& fields) const;
                                                                ^~~~~~
/data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/../MiLight/../MiLightState/GroupState.h:127:70: error: expected ',' or '...' before '<' token
   void applyState(JsonObject state, const BulbId& bulbId, std::vector<GroupStateField>& fields) const;
                                                                      ^
*** [/data/milight-bridge-back/.pioenvs/milight-bridge-back/libf5f/milight/lib/MiLight/CctPacketFormatter.cpp.o] Error 1
In file included from /data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/../MiLight/../MiLight/PacketFormatter.h:6,
                 from /data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/../MiLight/FUT02xPacketFormatter.h:1,
                 from /data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/FUT020PacketFormatter.h:1,
                 from /data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/FUT020PacketFormatter.cpp:1:
/data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/../MiLight/../MiLight/../MiLightState/GroupState.h:127:64: error: 'std::vector' has not been declared
   void applyState(JsonObject state, const BulbId& bulbId, std::vector<GroupStateField>& fields) const;
                                                                ^~~~~~
/data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/../MiLight/../MiLight/../MiLightState/GroupState.h:127:70: error: expected ',' or '...' before '<' token
   void applyState(JsonObject state, const BulbId& bulbId, std::vector<GroupStateField>& fields) const;
                                                                      ^
*** [/data/milight-bridge-back/.pioenvs/milight-bridge-back/libf5f/milight/lib/MiLight/FUT020PacketFormatter.cpp.o] Error 1
In file included from /data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/../MiLight/PacketFormatter.h:6,
                 from /data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/FUT02xPacketFormatter.h:1,
                 from /data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/FUT02xPacketFormatter.cpp:1:
/data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/../MiLight/../MiLightState/GroupState.h:127:64: error: 'std::vector' has not been declared
   void applyState(JsonObject state, const BulbId& bulbId, std::vector<GroupStateField>& fields) const;
                                                                ^~~~~~
/data/milight-bridge-back/.piolibdeps/milight-bridge-back/milight/src/lib/MiLight/../MiLight/../MiLight/../MiLightState/GroupState.h:127:70: error: expected ',' or '...' before '<' token
   void applyState(JsonObject state, const BulbId& bulbId, std::vector<GroupStateField>& fields) const;
                                                                      ^
*** [/data/milight-bridge-back/.pioenvs/milight-bridge-back/libf5f/milight/lib/MiLight/FUT02xPacketFormatter.cpp.o] Error 1
```

**Comment by shbatm** [comment]
Confirmed working still with v2022.11.5 of ESPHome, so maybe a bug in the beta?

**Comment by hencou** [comment]
Hi shbatm, thank you for reporting, solved!
